# Generated by Django 3.1.3 on 2022-12-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20221204_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='grad',
            new_name='grade',
        ),
    ]
